address=/mullvad.net/0.0.0.0
address=/appimage.github.io/0.0.0.0
address=/cloudflare-dns.com/0.0.0.0
address=/dns.nextdns.io/0.0.0.0
address=/mozilla.cloudflare-dns.com/0.0.0.0
address=/use-application-dns.net/0.0.0.0

