address=/use-application-dns.net/
address=/mozilla.cloudflare-dns.com/0.0.0.0
address=/cloudflare-dns.com/0.0.0.0
address=/1dot1dot1dot1.cloudflare-dns.com/0.0.0.0
address=/dns.nextdns.io/0.0.0.0
address=/dns.quad9.net/0.0.0.0
address=/dns.google/0.0.0.0
address=/dns.google.com/0.0.0.0
address=/dns.adguard-dns.com/0.0.0.0
address=/freedns.controld.com/0.0.0.0
address=/dns9.quad9.net/0.0.0.0
address=/dns10.quad9.net/0.0.0.0
address=/dns11.quad9.net/0.0.0.0
address=/doh.libredns.gr/0.0.0.0
address=/wikimedia-dns.org/0.0.0.0
address=/doh.dns4all.eu/0.0.0.0
address=/dns4all.eu/0.0.0.0
address=/doh.mullvad.net/0.0.0.0
address=/dns.mullvad.net/0.0.0.0
address=/pinterest.com/0.0.0.0

